# Generated by Django 6.0.6 on 2026-07-01 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('SEV1', 'Sev-1 (Critical)'), ('SEV2', 'Sev-2 (High)'), ('SEV3', 'Sev-3 (Medium)'), ('SEV4', 'Sev-4 (Low)')], max_length=4)),
                ('timeout_minutes', models.PositiveIntegerField(default=15, help_text='Minutes before escalation triggers for unacknowledged incidents.')),
                ('notify_oncall', models.BooleanField(default=True)),
                ('notify_admins', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Escalation Policies',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(editable=False, help_text='Human-readable incident ID (e.g., INC-1042)', max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('SEV1', 'Sev-1 (Critical)'), ('SEV2', 'Sev-2 (High)'), ('SEV3', 'Sev-3 (Medium)'), ('SEV4', 'Sev-4 (Low)')], default='SEV3', max_length=4)),
                ('status', models.CharField(choices=[('DECLARED', 'Declared'), ('ACKNOWLEDGED', 'Acknowledged'), ('INVESTIGATING', 'Investigating'), ('MITIGATING', 'Mitigating'), ('RESOLVED', 'Resolved'), ('POST_MORTEM', 'Post-Mortem')], default='DECLARED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('affected_services', models.JSONField(blank=True, default=list)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('COMMENT', 'Comment'), ('ASSIGNMENT', 'Assignment Change'), ('ESCALATION', 'Escalation')], default='COMMENT', max_length=20)),
                ('message', models.TextField()),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnCallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PostMortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('impact', models.TextField(blank=True, default='')),
                ('timeline_data', models.JSONField(blank=True, default=list)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('anomalies', models.JSONField(blank=True, default=list, help_text='List of anomaly objects detected by the XAI analyzer.')),
                ('xai_confidence', models.FloatField(blank=True, help_text='Overall confidence score of the XAI analysis (0.0 to 1.0).', null=True)),
                ('log_highlights', models.JSONField(blank=True, default=list, help_text='Highlighted log excerpts relevant to root cause.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postmortem', to='incidents.incident')),
            ],
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', '-created_at'], name='incidents_i_status_3b7181_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity', '-created_at'], name='incidents_i_severit_5e28cd_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['assignee', 'status'], name='incidents_i_assigne_df572d_idx'),
        ),
    ]
